In [46]:
# Utilities for object detector.

import numpy as np
import sys
import tensorflow as tf
import os
from threading import Thread
from datetime import datetime
import cv2

#from utils import label_map_util
#from object_detection.utils import label_map_util
from collections import defaultdict
import time
import copy
import matplotlib.pyplot as plt
%matplotlib inline
from imutils.video import VideoStream
from imutils import face_utils
import imutils
from PIL import Image
import math
import pandas as pd
from keras.preprocessing import image


In [47]:
detection_graph = tf.Graph()
#sys.path.append("..")

# score threshold for showing bounding boxes.
score_thresh = 0.25 #0.27

'''
MODEL_NAME = 'hand_inference_graph'
# Path to frozen detection graph. This is the actual model that is used for the object detection.
PATH_TO_CKPT = MODEL_NAME + '/frozen_inference_graph.pb'
# List of the strings that is used to add correct label for each box.
PATH_TO_LABELS = os.path.join(MODEL_NAME, 'hand_label_map.pbtxt')'''

NUM_CLASSES = 1

PATH_TO_CKPT = "model_data/frozen_inference_graph.pb"
PATH_TO_LABELS = "model_data/hand_label_map.pbtxt"

'''# load label map
label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(
    label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)'''



'# load label map\nlabel_map = label_map_util.load_labelmap(PATH_TO_LABELS)\ncategories = label_map_util.convert_label_map_to_categories(\n    label_map, max_num_classes=NUM_CLASSES, use_display_name=True)\ncategory_index = label_map_util.create_category_index(categories)'

In [48]:
import tensorflow as tf
from keras.models import load_model as lm
model = lm("/home/administrator/HG/VGG_cross_validated.h5", custom_objects = { "tf": tf })
'''gesture_names = {0: 'None',
                 1: 'Fist',
                 2: 'L',
                 3: 'Okay',
                 4: 'Palm',
                 5: 'Peace'}'''
gesture_names = {0: 'No hand---------------------',
                 1: 'Fist',
                 2: 'L- Shape',
                 3: 'Okay',
                 4: 'Hand',
                 5: 'Victory'}


# parameters
cap_region_x_begin = 0.5  # start point/total width
cap_region_y_end = 0.8  # start point/total width
threshold = 60  # binary threshold
blurValue = 41  # GaussianBlur parameter
bgSubThreshold = 50
learningRate = 0
# General Settings
prediction = ''
action = ''
score = 0
img_counter = 500
isBgCaptured = 0

bgModel = cv2.createBackgroundSubtractorMOG2(0, bgSubThreshold)

def predict_image(image):
    print("calling")
    image = np.array(image, dtype='float32')
    image /= 255
    pred_array = model.predict(image)

    # model.predict() returns an array of probabilities - 
    # np.argmax grabs the index of the highest probability.
    result = gesture_names[np.argmax(pred_array)]
    
    # A bit of magic here - the score is a float, but I wanted to
    # display just 2 digits beyond the decimal point.
    score = float("%0.2f" % (max(pred_array[0]) * 100))
    print(f'Result: {result}, Score: {score}')
    return result, score


def remove_background(frame):
    fgmask = bgModel.apply(frame, learningRate=learningRate)
    kernel = np.ones((3, 3), np.uint8)
    fgmask = cv2.erode(fgmask, kernel, iterations=1)
    res = cv2.bitwise_and(frame, frame, mask=fgmask)
    return res

def predict_rgb_image_vgg(image):
    image = np.array(image, dtype='float32')
    image /= 255
    pred_array = model.predict(image)
    print(f'pred_array: {pred_array}')
    result = gesture_names[np.argmax(pred_array)]
    print(f'Result: {result}')
    print(max(pred_array[0]))
    score = float("%0.2f" % (max(pred_array[0]) * 100))
    print(result)
    return result, score

In [68]:

# draw the detected bounding boxes on the images
# You can modify this to also draw a label.
def draw_box_on_image(num_hands_detect, score_thresh, scores, boxes, im_width, im_height, image_np):
    print("In side the draw boxes")
    print(num_hands_detect)
    for i in range(int(num_hands_detect[0])):
        if (scores[i] > score_thresh):
            (left, right, top, bottom) = (boxes[i][1] * im_width, boxes[i][3] * im_width,
                                          boxes[i][0] * im_height, boxes[i][2] * im_height) 
            p1 = (int(left), int(top))
            p2 = (int(right), int(bottom))
            cv2.rectangle(image_np, p1, p2, (77, 255, 9), 3, 1)
            Hand_crop_img = image_np[int(top) : int(bottom), int(left) : int(right)]                        
                              
            a = np.array(Hand_crop_img) 
            print(a,"-------------------========")
            if a.size != 0 and scores[i] > 0.8 :
                cv2.imshow("Hand", Hand_crop_img)
                #cv2.imshow("Hand", Hand_crop_img)
                img = remove_background(Hand_crop_img)
                cv2.imshow("Clip Removed BackGround",img)
                # convert the image into binary image
                gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
                blur = cv2.GaussianBlur(gray, (blurValue, blurValue), 0)
                ret, thresh = cv2.threshold(blur, threshold, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
                
                #Pridiction
                target = np.stack((thresh,) * 3, axis=-1)
                target = cv2.resize(target, (224, 224))
                target = target.reshape(1, 224, 224, 3)
                prediction, score = predict_rgb_image_vgg(target)

                # Draw the text
                cv2.putText(image_np, f"Prediction: {prediction} ({score}%)", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1,
                            (255, 0, 0),3)
                #v2.putText(image_np, f"Action: {action}", (50, 80), cv2.FONT_HERSHEY_SIMPLEX, 1,(0, 255, 0),2)  # Draw the text
                #cv2.imshow('original', frame)
                cv2.imshow('ori', thresh)

# Show fps value on image.
def draw_fps_on_image(fps, image_np):
    cv2.putText(image_np, str(fps), (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)

In [69]:

# Load a frozen infrerence graph into memory
def load_inference_graph():

    # load frozen tensorflow model into memory
    print("> ====== loading HAND frozen graph into memory")
    detection_graph = tf.Graph()
    with detection_graph.as_default():
        od_graph_def = tf.GraphDef()
        with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
            serialized_graph = fid.read()
            od_graph_def.ParseFromString(serialized_graph)
            tf.import_graph_def(od_graph_def, name='')
        sess = tf.Session(graph=detection_graph)
    print(">  ====== Hand Inference graph loaded.")
    #print (sess)
    #print (detection_graph)
    
    return detection_graph, sess

In [70]:
# Actual detection .. generate scores and bounding boxes given an image
def detect_objects(image_np, detection_graph, sess):
    # Definite input and output Tensors for detection_graph
    print("Detecting objects")
    image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
    # Each box represents a part of the image where a particular object was detected.
    detection_boxes = detection_graph.get_tensor_by_name(
        'detection_boxes:0')
    # Each score represent how level of confidence for each of the objects.
    # Score is shown on the result image, together with the class label.
    detection_scores = detection_graph.get_tensor_by_name(
        'detection_scores:0')
    detection_classes = detection_graph.get_tensor_by_name(
        'detection_classes:0')
    num_detections = detection_graph.get_tensor_by_name(
        'num_detections:0')

    image_np_expanded = np.expand_dims(image_np, axis=0)

    (boxes, scores, classes, num) = sess.run(
        [detection_boxes, detection_scores,
            detection_classes, num_detections],
        feed_dict={image_tensor: image_np_expanded})
    
    #print (boxes, "---------", scores, "-------", classes, "-------", num)
    #print(boxes.shape, "------------------")
    #print(scores.shape, "------------------")
    #print(classes.shape, "------------------")
    #print(num.shape, "------------------")
    #boxes =np.squeeze(boxes)
    #scores = np.squeeze(scores)
    #print(boxes.shape, "------------------")
    #print(scores.shape, "------------------")
    #print(num)
    return num, np.squeeze(boxes), np.squeeze(scores)

In [71]:
cap = cv2.VideoCapture(0) #uses webcam for video
cap.set(5, 30)
print(cap.get(3),cap.get(1))
frameRate = cap.get(5)
print(frameRate)
detection_graph, sess = load_inference_graph()
count=0
while True:
    count+=1             
    frameId = count
    ret, image_np = cap.read()
    t = time.time()
    print("forward = {}".format(time.time() - t))   #Time calculation
    #frameCopy = np.copy(image_np)
    #cv2.imshow('Input', image_np)
    im_width = image_np.shape[1]
    im_height = image_np.shape[0]
    #print(im_width,im_height)
    num, boxes, scores = detect_objects(image_np, detection_graph, sess)
    draw_box_on_image(num, score_thresh, scores, boxes, im_width, im_height, image_np)
    draw_fps_on_image(frameRate, image_np)
    cv2.imshow('OUt', image_np)
    print("Time Taken for frame = {}".format(time.time() - t)) #Time calculation for one frame
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
               
# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()
   

640.0 -1.0
30.0
> ====== loading HAND frozen graph into memory
>  ====== Hand Inference graph loaded.
forward = 9.059906005859375e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 1.6351304054260254
forward = 2.1457672119140625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.13518929481506348
forward = 3.337860107421875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.12640666961669922
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06766033172607422
forward = 2.1457672119140625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.04921293258666992
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9

In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [  4   9   8]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.07587957382202148
forward = 1.6689300537109375e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9

In side the draw boxes
[100.]
Time Taken for frame = 0.07095551490783691
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06562232971191406
forward = 2.384185791015625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.05302739143371582
forward = 2.384185791015625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.05350852012634277
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.07718157768249512
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.056513309478759766
forward = 3.0994415283203125e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.05877089500427246
forward = 2.384185791015625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06221580505371094
forward = 3.0994415283203125e-06
Detecting objects
In side the dr

In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [159 161 156]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]



pred_array: [[0.85814804 0.12688246 0.01090848 0.0024949  0.00156615]]
Result: No hand---------------------
0.85814804
No hand---------------------
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 17  17  22]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.3204464912414551
forward = 3.337860107421875e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  

In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [132 147 144]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
pred_array: [[9.1604239e-01 6.5347724e-02 1.6991107e-02 9.6591690e-04 6.5295934e-04]]
Result: No hand---------------------
0.9160424
No hand---------------------
Time Taken for frame = 0.41727423667907715
forward = 3.5762786865234375e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255

pred_array: [[9.1649210e-01 6.9646582e-02 1.3860608e-02 2.0356437e-07 5.7027700e-07]]
Result: No hand---------------------
0.9164921
No hand---------------------
Time Taken for frame = 0.34801650047302246
forward = 4.291534423828125e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [150 153 152]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.07869315147399902
forward = 2.86

pred_array: [[1.50422990e-01 1.18899599e-01 7.30445623e-01 1.13344744e-04
  1.18387652e-04]]
Result: L- Shape
0.7304456
L- Shape
Time Taken for frame = 0.3154730796813965
forward = 3.337860107421875e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [163 165 160]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
pred_array: [[6.4162321e-02 4.9440611e-02 8.8610190e-01 1.6943619e-04 1.2572973e-04]]
Resul

In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [  0   4   3]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.08306670188903809
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]


pred_array: [[7.9069633e-07 9.8242390e-01 1.4439408e-02 9.8550341e-09 3.1358227e-03]]
Result: Fist
0.9824239
Fist
Time Taken for frame = 0.36501288414001465
forward = 3.5762786865234375e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 91  98  92]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
pred_array: [[2.2144318e-06 9.0097493e-01 3.2321651e-02 1.6811110e-07 6.6701084e-02]]
Result: Fist
0.900

pred_array: [[1.9470126e-06 6.8440509e-01 2.4832359e-01 1.6872477e-07 6.7269191e-02]]
Result: Fist
0.6844051
Fist
Time Taken for frame = 0.3226022720336914
forward = 4.291534423828125e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [148 155 149]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
pred_array: [[1.25967767e-06 8.69588554e-01 1.24567434e-01 2.05297628e-08
  5.84280305e-03]]
Result: Fist


In side the draw boxes
[100.]
Time Taken for frame = 0.08052754402160645
forward = 3.0994415283203125e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06515002250671387
forward = 3.337860107421875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06632137298583984
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.09183716773986816
forward = 2.384185791015625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06205439567565918
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.07026243209838867
forward = 3.814697265625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.07920098304748535
forward = 3.814697265625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06417346000671387
forward = 3.0994415283203125e-06
Detecting objects
In side the draw b

In side the draw boxes
[100.]
Time Taken for frame = 0.07973599433898926
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.05613565444946289
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06443285942077637
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.05858778953552246
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06351518630981445
forward = 3.0994415283203125e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.05868959426879883
forward = 2.1457672119140625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.05962681770324707
forward = 2.1457672119140625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.05603218078613281
forward = 3.0994415283203125e-06
Detecting objects
In side th

pred_array: [[4.4746618e-03 9.7996569e-01 1.5265060e-02 1.3112093e-05 2.8144673e-04]]
Result: Fist
0.9799657
Fist
Time Taken for frame = 0.32564473152160645
forward = 4.0531158447265625e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [144 157 150]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
pred_array: [[3.4099608e-05 9.9891686e-01 1.0173183e-03 6.0575140e-08 3.1654767e-05]]
Result: Fist
0.998

pred_array: [[2.2328645e-06 9.9282068e-01 7.1413242e-03 5.9275194e-09 3.5771001e-05]]
Result: Fist
0.9928207
Fist
Time Taken for frame = 0.3302910327911377
forward = 3.814697265625e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [149 158 152]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
pred_array: [[4.18910395e-06 9.96116161e-01 3.84050142e-03 1.19954615e-08
  3.91601279e-05]]
Result: Fist
0.9

pred_array: [[1.9734473e-06 9.9326903e-01 6.3413898e-03 1.5051658e-08 3.8754620e-04]]
Result: Fist
0.993269
Fist
Time Taken for frame = 0.4205453395843506
forward = 4.76837158203125e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [145 157 155]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
pred_array: [[3.2565811e-07 9.9827266e-01 1.6854729e-03 7.3951034e-10 4.1484462e-05]]
Result: Fist
0.9982726

pred_array: [[5.6425961e-07 9.9863070e-01 1.3373953e-03 9.4177077e-10 3.1358642e-05]]
Result: Fist
0.9986307
Fist
Time Taken for frame = 0.32534146308898926
forward = 3.0994415283203125e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [148 160 158]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.07073378562927246
forward = 2.6226043701171875e-06
Detecting objects
In side th

In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [150 161 155]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.0895533561706543
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
 

In side the draw boxes
[100.]
Time Taken for frame = 0.08320212364196777
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [151 163 156]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.06462717056274414
forward = 3.0994415283203125e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06323504447937012
forward = 3.09944152832

pred_array: [[8.46027033e-05 8.85950089e-01 1.13283135e-01 2.05628976e-06
  6.80178928e-04]]
Result: Fist
0.8859501
Fist
Time Taken for frame = 0.31756162643432617
forward = 4.0531158447265625e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [149 157 153]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
pred_array: [[3.9511742e-05 9.6947497e-01 3.0356232e-02 2.0954910e-07 1.2909620e-04]]
Result: Fis

forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06556200981140137
forward = 3.337860107421875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06353163719177246
forward = 2.384185791015625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.055561065673828125
forward = 2.384185791015625e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [162 163 160]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 25

pred_array: [[1.2187104e-04 8.6799467e-01 9.3157917e-02 2.3806299e-04 3.8487460e-02]]
Result: Fist
0.86799467
Fist
Time Taken for frame = 0.368427038192749
forward = 4.0531158447265625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.07983613014221191
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.0688173770904541
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 33  38  37]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255

pred_array: [[1.3165169e-03 6.5362412e-01 3.3279893e-01 5.9831716e-05 1.2200640e-02]]
Result: Fist
0.6536241
Fist
Time Taken for frame = 0.3247220516204834
forward = 4.0531158447265625e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [154 166 157]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.07546639442443848
forward = 2.6226043701171875e-06
Detecting objects
In side the

In side the draw boxes
[100.]
Time Taken for frame = 0.08116579055786133
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 97 106 105]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.07139039039611816
forward = 3.5762786865234375e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255  

In side the draw boxes
[100.]
Time Taken for frame = 0.08503460884094238
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [155 165 163]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.06932449340820312
forward = 3.0994415283203125e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255

In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [151 166 161]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.08557820320129395
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9

In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [171 173 168]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.07215023040771484
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9

In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 23  38  54]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.09119963645935059
forward = 3.0994415283203125e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9

pred_array: [[0.61444545 0.12815432 0.25573435 0.00081481 0.00085105]]
Result: No hand---------------------
0.61444545
No hand---------------------
Time Taken for frame = 0.41063547134399414
forward = 8.821487426757812e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 14  31  42]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
pred_array: [[9.79920566e-01 4.88353195e-03 1.48458425e-02 2.53957347e-

pred_array: [[1.3215457e-04 1.6721223e-02 9.8313439e-01 1.8137216e-06 1.0524155e-05]]
Result: L- Shape
0.9831344
L- Shape
Time Taken for frame = 0.3557271957397461
forward = 3.5762786865234375e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 13  33  35]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
pred_array: [[2.7796169e-04 2.4140680e-04 9.9944335e-01 2.8453504e-05 8.7359695e-06]]
Result: L- 

pred_array: [[9.5556285e-03 2.8315172e-04 9.8992622e-01 1.8882884e-04 4.6152505e-05]]
Result: L- Shape
0.9899262
L- Shape
Time Taken for frame = 0.3647646903991699
forward = 3.814697265625e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 21  40  50]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
pred_array: [[8.30045715e-03 1.24366226e-04 9.91519034e-01 4.25125654e-05
  1.35625605e-05]]
Result: 

pred_array: [[3.4270016e-03 6.4146137e-05 9.9648970e-01 1.3259376e-05 5.8537566e-06]]
Result: L- Shape
0.9964897
L- Shape
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 ...

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [157 173 166]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]

 [[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]]] -------------------========
Time Taken for frame = 0.4998660087585449
forward = 5.9604644775390625e-06
Detecting objects
In side the draw boxes
[100.]
[[[ 77 255   9]
  [ 77 255   9]
  [ 77 255   9]
  ...
  [ 77 255   9]
  [ 77 255   9]
  [ 77 255 

In side the draw boxes
[100.]
Time Taken for frame = 0.07921743392944336
forward = 3.337860107421875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.0636138916015625
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06467843055725098
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.07898759841918945
forward = 3.5762786865234375e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06025528907775879
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06336617469787598
forward = 2.384185791015625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06639790534973145
forward = 3.5762786865234375e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06833386421203613
forward = 3.0994415283203125e-06
Detecting objects
In side the d

In side the draw boxes
[100.]
Time Taken for frame = 0.07737064361572266
forward = 3.0994415283203125e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.05946612358093262
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.05622529983520508
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.056697845458984375
forward = 2.1457672119140625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06946659088134766
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.05756521224975586
forward = 3.0994415283203125e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.0636451244354248
forward = 2.1457672119140625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.055457353591918945
forward = 2.6226043701171875e-06
Detecting objects
In side t

In side the draw boxes
[100.]
Time Taken for frame = 0.08325672149658203
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.05797863006591797
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06415128707885742
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06546401977539062
forward = 3.814697265625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.07710909843444824
forward = 3.0994415283203125e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06971406936645508
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.08228111267089844
forward = 2.384185791015625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06275391578674316
forward = 2.384185791015625e-06
Detecting objects
In side the draw

In side the draw boxes
[100.]
Time Taken for frame = 0.07145905494689941
forward = 2.6226043701171875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.05507946014404297
forward = 2.384185791015625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06425285339355469
forward = 3.337860107421875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.0630037784576416
forward = 2.86102294921875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.08167123794555664
forward = 8.58306884765625e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06528711318969727
forward = 3.337860107421875e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.08469009399414062
forward = 3.5762786865234375e-06
Detecting objects
In side the draw boxes
[100.]
Time Taken for frame = 0.06844544410705566
forward = 2.1457672119140625e-06
Detecting objects
In side the draw